### ISSUE TITLE
Especificação do Problema

### ISSUE THREAD

**Issue by philippemesquita** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-comprai#2]

**Comment by VainestFall2** [comment]
- [ ] Personas @VainestFall2 
- [ ] Histórias de Usuários @VainestFall2 
- [ ] Modelagem do Processo de Negócio
- [ ] Indicadores de Desempenho
- [ ] Requisitos
- [ ] Restrições
- [ ] Diagrama de Casos de Uso
- [ ] Matriz de Rastreabilidade
- [ ] Gerenciamento de Tempo
- [ ] Gerenciamento de Equipe
- [ ] Gestão de Orçamento

**Comment by philippemesquita** [comment]
Fiz alguns exemplos de Personas, Histórias de Usuários, requisitos funcionais e não funcionais, restrições e também um esboço do diagrama de caso de uso.

**Comment by philippemesquita** [comment]
Update Especificação do Projeto
Atualizado os itens Personas, Histórias de Usuários, Requisitos Funcionais e não Funcionais e Restrições.

**Comment by ErculesM** [comment]
Subi o "gráfico" com o gerenciamento de equipe

**Comment by Pedro-HFC** [comment]
Feito Gerenciamento de tempo.

**Comment by philippemesquita** [comment]
Deve ser feitos para entrega da etapa 2:

[] Modelagem do Processo de Negócio
[] Indicadores de Desempenho
